# Generated by Django 4.2.6 on 2024-12-14 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0006_disnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='user_image')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('utype', models.CharField(default='user', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerCollectionCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('aadhaar', models.CharField(default='', max_length=100)),
                ('skills_exp', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('utype', models.CharField(default='volcc', max_length=100)),
                ('assigned_collection_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_volunteers', to='adminapp.collectioncenter')),
                ('collection_center_select', models.ManyToManyField(blank=True, related_name='volunteer_selections', to='adminapp.collectioncenter')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('aadhaar', models.CharField(default='', max_length=100)),
                ('skills_exp', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('utype', models.CharField(default='volcmp', max_length=100)),
                ('assigned_camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_volunteers', to='adminapp.camp')),
                ('camp_select', models.ManyToManyField(blank=True, related_name='volunteer_selections', to='adminapp.camp')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_recieved', models.DateTimeField(auto_now_add=True)),
                ('collectioncenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='adminapp.collectioncenter')),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('quantity', models.PositiveIntegerField(default='0')),
                ('date_recieved', models.DateTimeField(auto_now_add=True)),
                ('collectioncenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='adminapp.collectioncenter')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='dis_app.resources')),
            ],
        ),
    ]
