# Generated by Django 4.1.4 on 2024-10-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_camp_collectioncenter_delete_camps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='gmap_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectioncenter',
            name='gmap_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
