# Generated by Django 4.1.4 on 2024-10-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_camp_gmap_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncenter',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='collect_pics/'),
        ),
    ]
